### ISSUE TITLE
Doesn't understand fermitools install

### ISSUE THREAD

**Issue by kialio** [fermi-lat/ScienceTools-conda-recipe#7]
Hi,

If I do this:

> conda create -n fermi python=2.7 -c conda-forge -c fermi_dev_externals fermitools

I get a 'fermitools command not understood' and I have to install them in the new environment later. 

Jeremy

**Comment by jasercion** [comment]
Since python=2.7 is referencing a specific package to install it needs to be in the same argument block as fermitools.  From what I can tell conda processes all package installation requests at once, so after it read the python=2.7 request in your command followed by a flag it assumed that no other inputs are references to packages to be installed. Either

`conda create -n fermi python=2.7 fermitools -c conda-forge -c fermi_dev_externals fermitools`
or 
`conda create -n fermi fermitools -c conda-forge -c fermi_dev_externals python=2.7 fermitools`

**Comment by kialio** [comment]
Ah, yea, that was user error.  I verify that this works:

`conda create -n fermi -c conda-forge -c fermi_dev_externals python=2.7 fermitools`
